Feature/3 modal
today-they-learned/peacepiece_front pull request #5
Opened 2022-07-20 11:59 UTC by soyekwon

![스크린샷(17)](https://user-images.githubusercontent.com/55877726/179976092-a3319b35-2fa6-4550-bb58-735ca96dc7bb.png)
- children으로 질문 내용을 바꿀 수 있게 구현했습니다.

2022-07-21 01:47 UTC, minjj0905 requested changes

2022-07-21 01:47 UTC, minjj0905 commented on src/components/Modal/ModalFrame.tsx
> +export default ModalFrame;
end of Line 😢

2022-07-21 01:47 UTC, minjj0905 commented on .eslintrc.js
> +        endOfLine: "auto",
이건 설정끄면 안됩니당

2022-07-22 06:07 UTC, soyekwon commented on .eslintrc.js
> +        endOfLine: "auto",
넴 지울게여

2022-07-22 12:08 UTC, soyekwon commented on src/components/Modal/ModalFrame.tsx
> +export default ModalFrame;
?-? 이해를 못했어여

2022-07-22 12:09 UTC, soyekwon commented on src/components/Modal/ModalFrame.tsx
> +
공용 컴포넌트 components/common 위치에 만들면 될까유 ?

2022-07-23 08:22 UTC, minjj0905 commented on src/components/Modal/ModalFrame.tsx
> +export default ModalFrame;
코드의 맨 마지막 줄은 항상 빈 라인이 있어야 해용 안그럼 깃에서 원래있던 코드를 수정된걸로 처리해서 ,,

2022-07-23 08:36 UTC, minjj0905 commented on src/components/Modal/ModalFrame.tsx
> +
굿굿

2022-07-23 09:03 UTC, minjj0905 commented on src/components/Modal/ModalFrame.tsx
> +  const [modalIsOpen, setModalIsOpen] = useState(true);
```useState<boolean>(true)```

이런식으로 제네릭으로 타입 명시 해주면 좋을듯요!

2022-07-23 12:12 UTC, cychann reviewed
코드 잘봤습니다👍

2022-07-23 12:12 UTC, cychann commented on src/components/Modal/ModalFrame.tsx
> +const Close = styled.img.attrs({
오...이렇게도 되는걸 이제 알았네요

2022-07-26 17:06 UTC, soyekwon commented on src/components/Modal/ModalFrame.tsx
> +const Close = styled.img.attrs({
ㅎㅎ

2022-07-27 12:03 UTC, minjj0905 submitted a review, later dismissed

2022-08-02 06:07 UTC, minjj0905 submitted a review, later dismissed

2022-08-08 12:08 UTC, minjj0905 submitted a review, later dismissed

2022-08-10 06:53 UTC, minjj0905 commented
이건 리뷰 무시하고 머지하세용

2022-08-11 06:43 UTC, merged