Feature/navbar
today-they-learned/peacepiece_front pull request #6
Opened 2022-07-22 16:07 UTC by cychann

- navbar 작업했습니다 (Mobile / Desktop)
- 반응형 레이아웃 틀 추가했습니다
- 각 메뉴 클릭했을 때 해당 url로 이동하도록 추가해줬습니다
- 로그인 / 로그아웃 2가지 경우 navbar 모두 만들었고, 현재는 주석으로 처리해놨습니다

![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/66055587/180479469-0fa41983-6869-4a10-a7b1-94bde3842f9e.gif)

![스크린샷 2022-07-23 오전 1 06 51](https://user-images.githubusercontent.com/66055587/180479583-334e8c66-9683-478f-8994-a8f5b08a83a0.png)

2022-07-23 08:39 UTC, minjj0905 requested changes
코드의 마지막줄엔,, 엔터를 칩시다... 프리티어 설정이 꺼졌나?

2022-07-23 08:39 UTC, minjj0905 commented on src/components/Navbar/DesktopNavbar.tsx
> +`;
공통되는 컴포넌트 어떡할지 우리 오늘 회의에서 이야기해보아요,,,

2022-07-23 09:04 UTC, minjj0905 commented on src/components/Navbar/DesktopNavbar.tsx
> +  const [currentClickNav, setCurrentClickNav] = useState("island");
```useState<string>("island")```
이런식으로 타입 명시하는 습관을 들여봅시다

2022-07-23 12:20 UTC, cychann commented on src/components/Navbar/DesktopNavbar.tsx
> +`;
코드상에는 엔터 되어있는데 뭔가 잘못됐나봐욥...
네 오늘 회의 때 얘기해봅시당

2022-07-26 17:04 UTC, soyekwon submitted a review, later dismissed
코드 잘 봤습니다 !

2022-07-27 12:06 UTC, minjj0905 commented on src/constants/color.js
> +  MAINCOLOR: "#3CE87B",
여기 제가 primary로 넣었는데,, 오늘 병합하면서 수정합세다

2022-07-27 12:06 UTC, minjj0905 submitted a review, later dismissed

2022-08-02 11:18 UTC, merged